### ISSUE TITLE
To do before initial launch

### ISSUE THREAD

**Issue by aviflax** [aviflax/vax.help#3]
## Features
- [x] Subscription verifications
  - [x] (background job) send subscription verification emails
  - [x] (web) handle subscription verification requests
  - [x] (web) generate an actual nonce when creating a subscription
  - [ ] ~~Maybe wrap each subscription verification in its own transaction~~
- [x] Availability Update and Notifications (you know, the whole point of this thing) — details in #13
  - [x] (background job) poll for availability updates and insert them and … enqueue update notifications
  - [ ] ~~When a subscription is validated, an alert should be sent out immediately if any of the subscription's locations have availability~~ (#20)
- [ ] ~~Set up basic analytics~~ (#25)
  - Perhaps Fathom, or [Shynet](https://render.com/docs/deploy-shynet)

## Misc

- [x] Add `providerId` to db and use it instead of auto-generated id
- [x] Create team@vax.help and update link
- [ ] ~~Add sentry~~ (broken out to #24)
- [ ] ~~Set up auto scaling~~ (premature)
- [ ] ~~Adopt mulog everywhere~~ (not crucial)
- [x] Use JSON logger publisher
- [ ] ~~Maybe use "alert" or "update" rather than “notification”~~ (not crucial)
- [ ] ~~Background workers process shouldn't crash on error but should definitely catch and log exceptions~~
  - Rather, send alert via e.g. Sentry or something similar, then continue. But make sure whatever was being worked on isn't lost. But also doesn't keep blocking the head of the queue.
  - Maybe use Faktory (#10)
  - *Update* I think maybe this is two separate things: error handling+logging (#24) and using a job queue to handle retries (#10)

## Web 
- [x] Retrieve locations on start
- [x] insert subscriptions, not subscription requests
- [x] use location ID in form post rather than the name
- [x] fix rendering (size/zoom) on phones

## DB
- [x] new table: feed.updates
- [ ] ~~new table: availability.notifications~~ (not doing this for now, ran out of time)

**Comment by aviflax** [comment]
Change my email address to avi@vax.help.

**Comment by aviflax** [comment]
Set up auto scaling.

**Comment by aviflax** [comment]
Add sentry.

**Comment by aviflax** [comment]
Use JSON logger publisher.

**Comment by aviflax** [comment]
Adopt mulog everywhere

**Comment by aviflax** [comment]
Create team@vax.help and update link.

**Comment by aviflax** [comment]
Maybe wrap each subscription verification in its own transaction.

**Comment by aviflax** [comment]
When a subscription is validated, an alert should be sent out immediately if any of the subscription's locations have availability.

**Comment by aviflax** [comment]
Maybe use "alert" or "update" rather than "notification"

**Comment by aviflax** [comment]
Background workers process shouldn't crash on error.

Rather, send alert via e.g. Sentry or something similar, then continue. But make sure whatever was being worked on isn't lost. But also doesn't keep blocking the head of the queue.

**Comment by aviflax** [comment]
Close enough!
